### ISSUE TITLE
The zenodo link is invalid

### ISSUE THREAD

**Issue by TangYiChing** [hosseinshn/MOLI#1]
Is it possible to provide the link to harmonized data again?

**Comment by hosseinshn** [comment]
The link works on our end (we tested it with multiple devices). Can you please be more specific about the error(?) you are getting?

**Comment by TangYiChing** [comment]
> 
> 
> The link works on our end (we tested it with multiple devices). Can you please be more specific about the error(?) you are getting?

Thank you. It works perfect now, before it was an empty page (perhaps an error from zenodo side).
